import { Movie } from './types';

export const MOCK_MOVIES: Movie[] = [
  {
    id: '1',
    title: 'The Godfather',
    year: 1972,
    genre: ['Drama', 'Crime'],
    imdbRating: 9.2,
    rottenTomatoes: 97,
    personalRating: 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjg5ZGNmZWMtY2ZmNy00OWFiLThkMjAtMjRlNDYzZDJkNThlXkEyXkFqcGc@._V1_FMjpg_UY2908_.jpg',
    badge: 'Classic',
    isFavorite: true,
    director: 'Francis Ford Coppola',
    language: 'English',
    runtime: '175 min',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan', 'Richard S. Castellano'],
    trailerUrl: 'https://www.youtube.com/embed/sY1S34973zA',
  },
  {
    id: '2',
    title: 'Inception',
    year: 2010,
    genre: ['Sci-Fi', 'Action'],
    imdbRating: 8.8,
    rottenTomatoes: 87,
    personalRating: 3,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjQwNGE0MjctMDA3Yi00MGEyLTkyNTAtMjcxMTYxOWE0ZWRkXkEyXkFqcGc@._V1_FMjpg_UX989_.jpg',
    badge: 'New',
    isFavorite: false,
    director: 'Christopher Nolan',
    language: 'English',
    runtime: '148 min',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy'],
    trailerUrl: 'https://www.youtube.com/embed/YoHD9XEInc0',
  },
  {
    id: '3',
    title: 'Pulp Fiction',
    year: 1994,
    genre: ['Crime', 'Drama'],
    imdbRating: 8.9,
    rottenTomatoes: 92,
    personalRating: 4,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZTRjYmY1NmYtMmU0Ny00OWQ4LWI5ZDUtMDE0MzU1YWZjYTFhXkEyXkFqcGc@._V1_.jpg',
    badge: 'Classic',
    isFavorite: true,
    director: 'Quentin Tarantino',
    language: 'English',
    runtime: '154 min',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson', 'Bruce Willis'],
    trailerUrl: 'https://www.youtube.com/embed/s7EdQ4FqbhY',
  },
  {
    id: '4',
    title: 'Parasite',
    year: 2019,
    genre: ['Drama', 'Thriller'],
    imdbRating: 8.5,
    rottenTomatoes: 99,
    personalRating: 2,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_.jpg',
    badge: 'New',
    isFavorite: false,
    director: 'Bong Joon-ho',
    language: 'Korean',
    runtime: '132 min',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik'],
    trailerUrl: 'https://www.youtube.com/embed/5xH0HfJHsaY',
  },
  {
    id: '5',
    title: 'Blade Runner',
    year: 1982,
    genre: ['Sci-Fi', 'Thriller'],
    imdbRating: 8.1,
    rottenTomatoes: 89,
    personalRating: 4,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BM2E5NWNiYWMtMDY0OS00MmIwLWI2MDctNjA5Y2NmZGJlNjQ4XkEyXkFqcGc@._V1_.jpg',
    badge: 'Classic',
    isFavorite: true,
    director: 'Ridley Scott',
    language: 'English',
    runtime: '117 min',
    cast: ['Harrison Ford', 'Rutger Hauer', 'Sean Young', 'Edward James Olmos'],
    trailerUrl: 'https://www.youtube.com/embed/eogpIG53Cis',
  },
  {
    id: '6',
    title: 'The Dark Knight',
    year: 2008,
    genre: ['Action', 'Crime'],
    imdbRating: 9.0,
    rottenTomatoes: 94,
    personalRating: 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMDQ5MWU2YWUtNTQ4OC00Njk5LWI0NzctMjM4OGZiNmZmNGViXkEyXkFqcGc@._V1_.jpg',
    badge: 'New',
    isFavorite: true,
    director: 'Christopher Nolan',
    language: 'English',
    runtime: '152 min',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Maggie Gyllenhaal'],
    trailerUrl: 'https://www.youtube.com/embed/EXeTwQWrcwY',
  },
  {
    id: '7',
    title: 'Mad Max- Fury Road',
    year: 2015,
    genre: ['Action', 'Sci-Fi'],
    imdbRating: 8.1,
    rottenTomatoes: 97,
    personalRating: 4,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNTU2ZDkzMzItOWViYi00Yzg1LWJhZjItNjRhMGI1M2U4MGRhXkEyXkFqcGc@._V1_.jpg',
    badge: 'Now',
    isFavorite: false,
    director: 'George Miller',
    language: 'English',
    runtime: '120 min',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult', 'Hugh Keays-Byrne'],
    trailerUrl: 'https://www.youtube.com/embed/hEJnMQG9ev8',
  },
  {
    id: '8',
    title: 'Fight Club',
    year: 1999,
    genre: ['Drama'],
    imdbRating: 8.8,
    rottenTomatoes: 79,
    personalRating: 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMzgyZThmZDctNjkwYi00YzU1LWFlY2UtYTIzNmIxZTdlZjVhXkEyXkFqcGc@._V1_.jpg',
    badge: 'Classic',
    isFavorite: true,
    director: 'David Fincher',
    language: 'English',
    runtime: '139 min',
    cast: ['Brad Pitt', 'Edward Norton', 'Meat Loaf', 'Jared Leto'],
    trailerUrl: 'https://www.youtube.com/embed/qtRKdVHc-cE',
  },
  {
    id: '9',
    title: "Schindler's List",
    year: 1993,
    genre: ['Drama', 'History'],
    imdbRating: 9.0,
    rottenTomatoes: 98,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjAzNTg4MzUtNzBjNC00OGE1LWE3YmQtYWNiY2UwYWJlY2YxXkEyXkFqcGc@._V1_.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Steven Spielberg',
    language: 'English',
    runtime: '195 min',
    cast: ['Liam Neeson', 'Ben Kingsley', 'Ralph Fiennes', 'Caroline Goodall'],
    trailerUrl: 'https://www.youtube.com/embed/gG22XNhtnoY',
  },
  {
    id: '10',
    title: 'Forrest Gump',
    year: 1994,
    genre: ['Drama', 'Romance'],
    imdbRating: 8.8,
    rottenTomatoes: 71,
    personalRating: 3,
    posterUrl: 'https://m.media-amazon.com/images/I/613ZgTigTpL.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Robert Zemeckis',
    language: 'English',
    runtime: '142 min',
    cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise', 'Mykelti Williamson'],
    trailerUrl: 'https://www.youtube.com/embed/bLvqoHBptjg',
  },
  {
    id: '11',
    title: 'The Matrix',
    year: 1999,
    genre: ['Action', 'Sci-Fi'],
    imdbRating: 8.7,
    rottenTomatoes: 83,
    personalRating: 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYjM1YzE0MzMtMDM4Ni00M2M4LWEyYzItNGFjMDkxZTcyNTEyXkEyXkFqcGc@._V1_.jpg',
    badge: 'Classic',
    isFavorite: true,
    director: 'Lana Wachowski',
    language: 'English',
    runtime: '136 min',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving'],
    trailerUrl: 'https://www.youtube.com/embed/vKQi3bBA1y8',
  },
];
