import { Movie } from './types';

const RECENTLY_ADDED_DATE = 1777448600000;

export const MOCK_MOVIES: Movie[] = [
  {
    id: '1',
    title: 'The Godfather',
    year: 1972,
    genre: ['Drama', 'Crime'],
    imdbRating: 9.2,
    rottenTomatoes: 97,
    personalRating: 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjg5ZGNmZWMtY2ZmNy00OWFiLThkMjAtMjRlNDYzZDJkNThlXkEyXkFqcGc@._V1_FMjpg_UY2908_.jpg',
    badge: 'Classic',
    isFavorite: true,
    director: 'Francis Ford Coppola',
    language: 'English',
    runtime: '175 min',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan', 'Richard S. Castellano'],
    trailerUrl: 'https://www.youtube.com/embed/sY1S34973zA',
    dateAdded: 1710831897000, // Older than 24h
  },
  {
    id: '2',
    title: 'Inception',
    year: 2010,
    genre: ['Sci-Fi', 'Action'],
    imdbRating: 8.8,
    rottenTomatoes: 87,
    personalRating: 3,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjQwNGE0MjctMDA3Yi00MGEyLTkyNTAtMjcxMTYxOWE0ZWRkXkEyXkFqcGc@._V1_FMjpg_UX989_.jpg',
    badge: 'New',
    isFavorite: false,
    director: 'Christopher Nolan',
    language: 'English',
    runtime: '148 min',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy'],
    trailerUrl: 'https://www.youtube.com/embed/YoHD9XEInc0',
    dateAdded: 1710831897000,
  },
  {
    id: '3',
    title: 'Pulp Fiction',
    year: 1994,
    genre: ['Crime', 'Drama'],
    imdbRating: 8.9,
    rottenTomatoes: 92,
    personalRating: 4,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZTRjYmY1NmYtMmU0Ny00OWQ4LWI5ZDUtMDE0MzU1YWZjYTFhXkEyXkFqcGc@._V1_.jpg',
    badge: 'Classic',
    isFavorite: true,
    director: 'Quentin Tarantino',
    language: 'English',
    runtime: '154 min',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson', 'Bruce Willis'],
    trailerUrl: 'https://www.youtube.com/embed/s7EdQ4FqbhY',
    dateAdded: 1710831897000,
  },
  {
    id: '4',
    title: 'Parasite',
    year: 2019,
    genre: ['Drama', 'Thriller'],
    imdbRating: 8.5,
    rottenTomatoes: 99,
    personalRating: 2,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_.jpg',
    badge: 'New',
    isFavorite: false,
    director: 'Bong Joon-ho',
    language: 'Korean',
    runtime: '132 min',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik'],
    trailerUrl: 'https://www.youtube.com/embed/5xH0HfJHsaY',
    dateAdded: 1710831897000,
  },
  {
    id: '5',
    title: 'Blade Runner',
    year: 1982,
    genre: ['Sci-Fi', 'Thriller'],
    imdbRating: 8.1,
    rottenTomatoes: 89,
    personalRating: 4,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BM2E5NWNiYWMtMDY0OS00MmIwLWI2MDctNjA5Y2NmZGJlNjQ4XkEyXkFqcGc@._V1_.jpg',
    badge: 'Classic',
    isFavorite: true,
    director: 'Ridley Scott',
    language: 'English',
    runtime: '117 min',
    cast: ['Harrison Ford', 'Rutger Hauer', 'Sean Young', 'Edward James Olmos'],
    trailerUrl: 'https://www.youtube.com/embed/eogpIG53Cis',
    dateAdded: 1710831897000,
  },
  {
    id: '6',
    title: 'The Dark Knight',
    year: 2008,
    genre: ['Action', 'Crime'],
    imdbRating: 9.0,
    rottenTomatoes: 94,
    personalRating: 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMDQ5MWU2YWUtNTQ4OC00Njk5LWI0NzctMjM4OGZiNmZmNGViXkEyXkFqcGc@._V1_.jpg',
    badge: 'New',
    isFavorite: true,
    director: 'Christopher Nolan',
    language: 'English',
    runtime: '152 min',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Maggie Gyllenhaal'],
    trailerUrl: 'https://www.youtube.com/embed/EXeTwQWrcwY',
    dateAdded: 1710831897000,
  },
  {
    id: '7',
    title: 'Mad Max- Fury Road',
    year: 2015,
    genre: ['Action', 'Sci-Fi'],
    imdbRating: 8.1,
    rottenTomatoes: 97,
    personalRating: 4,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNTU2ZDkzMzItOWViYi00Yzg1LWJhZjItNjRhMGI1M2U4MGRhXkEyXkFqcGc@._V1_.jpg',
    badge: 'Now',
    isFavorite: false,
    director: 'George Miller',
    language: 'English',
    runtime: '120 min',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult', 'Hugh Keays-Byrne'],
    trailerUrl: 'https://www.youtube.com/embed/hEJnMQG9ev8',
    dateAdded: 1710831897000,
  },
  {
    id: '8',
    title: 'Fight Club',
    year: 1999,
    genre: ['Drama'],
    imdbRating: 8.8,
    rottenTomatoes: 79,
    personalRating: 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMzgyZThmZDctNjkwYi00YzU1LWFlY2UtYTIzNmIxZTdlZjVhXkEyXkFqcGc@._V1_.jpg',
    badge: 'Classic',
    isFavorite: true,
    director: 'David Fincher',
    language: 'English',
    runtime: '139 min',
    cast: ['Brad Pitt', 'Edward Norton', 'Meat Loaf', 'Jared Leto'],
    trailerUrl: 'https://www.youtube.com/embed/qtRKdVHc-cE',
    dateAdded: 1710831897000,
  },
  {
    id: '9',
    title: "Schindler's List",
    year: 1993,
    genre: ['Drama', 'History'],
    imdbRating: 9.0,
    rottenTomatoes: 98,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjAzNTg4MzUtNzBjNC00OGE1LWE3YmQtYWNiY2UwYWJlY2YxXkEyXkFqcGc@._V1_.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Steven Spielberg',
    language: 'English',
    runtime: '195 min',
    cast: ['Liam Neeson', 'Ben Kingsley', 'Ralph Fiennes', 'Caroline Goodall'],
    trailerUrl: 'https://www.youtube.com/embed/gG22XNhtnoY',
    dateAdded: 1710831897000,
  },
  {
    id: '10',
    title: 'Forrest Gump',
    year: 1994,
    genre: ['Drama', 'Romance'],
    imdbRating: 8.8,
    rottenTomatoes: 71,
    personalRating: 3,
    posterUrl: 'https://m.media-amazon.com/images/I/613ZgTigTpL.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Robert Zemeckis',
    language: 'English',
    runtime: '142 min',
    cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise', 'Mykelti Williamson'],
    trailerUrl: 'https://www.youtube.com/embed/bLvqoHBptjg',
    dateAdded: 1710831897000,
  },
  {
    id: '11',
    title: 'The Matrix',
    year: 1999,
    genre: ['Action', 'Sci-Fi'],
    imdbRating: 8.7,
    rottenTomatoes: 83,
    personalRating: 5,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYjM1YzE0MzMtMDM4Ni00M2M4LWEyYzItNGFjMDkxZTcyNTEyXkEyXkFqcGc@._V1_.jpg',
    badge: 'Classic',
    isFavorite: true,
    director: 'Lana Wachowski',
    language: 'English',
    runtime: '136 min',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving'],
    trailerUrl: 'https://www.youtube.com/embed/vKQi3bBA1y8',
    dateAdded: 1710831897000,
  },
  {
    id: 'tt0066921',
    title: 'A Clockwork Orange',
    year: 1971,
    genre: ['Crime', 'Sci-Fi'],
    imdbRating: 8.2,
    rottenTomatoes: 86,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTY3MjM1Mzc4N15BMl5BanBnXkFtZTgwODM0NzAxMDE@._V1_SX300.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Stanley Kubrick',
    language: 'English',
    runtime: '136 min',
    cast: ['Malcolm McDowell', 'Patrick Magee', 'Michael Bates'],
    trailerUrl: 'https://www.youtube.com/embed/T54uZPI4Z8A',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0078748',
    title: 'Alien',
    year: 1979,
    genre: ['Horror', 'Sci-Fi'],
    imdbRating: 8.5,
    rottenTomatoes: 93,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BN2NhMDk2MmEtZDQzOC00MmY5LThhYzAtMDdjZGFjOGZjMjdjXkEyXkFqcGc@._V1_QL75_UX380_CR0,6,380,562_.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Ridley Scott',
    language: 'English',
    runtime: '117 min',
    cast: ['Sigourney Weaver', 'Tom Skerritt', 'John Hurt'],
    trailerUrl: 'https://www.youtube.com/embed/2TBKRQ4OwQc',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt1016150',
    title: 'All Quiet on the Western Front',
    year: 2022,
    genre: ['Drama', 'History', 'War'],
    imdbRating: 7.8,
    rottenTomatoes: 90,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BOWJiYWMyYTktZThhOS00ZjgxLWE0YTQtZDMyNTQxMjMyYjI2XkEyXkFqcGc@._V1_SX300.jpg',
    badge: 'New',
    isFavorite: false,
    director: 'Edward Berger',
    language: 'German, French',
    runtime: '148 min',
    cast: ['Felix Kammerer', 'Albrecht Schuch', 'Aaron Hilmer'],
    trailerUrl: 'https://www.youtube.com/embed/hf8EYbVxtCY',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0052561',
    title: 'Anatomy of a Murder',
    year: 1959,
    genre: ['Drama', 'Mystery'],
    imdbRating: 8.0,
    rottenTomatoes: 100,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYWRiNmViOGEtODY5OC00YTgxLWI3NjktZjBlOTBhM2ExNTU5XkEyXkFqcGc@._V1_SX300.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Otto Preminger',
    language: 'English',
    runtime: '161 min',
    cast: ['James Stewart', 'Lee Remick', 'Ben Gazzara'],
    trailerUrl: 'https://www.youtube.com/embed/rttoa1A5c-s',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0078788',
    title: 'Apocalypse Now',
    year: 1979,
    genre: ['Drama', 'Mystery', 'War'],
    imdbRating: 8.4,
    rottenTomatoes: 91,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZDhiMTljYjYtODc1Yy00MmEwLTg2OTYtYmE1YTRmNDE4MmEwXkEyXkFqcGc@._V1_QL75_UX380_CR0,11,380,562_.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Francis Ford Coppola',
    language: 'English, French, Vietnamese',
    runtime: '147 min',
    cast: ['Martin Sheen', 'Marlon Brando', 'Robert Duvall'],
    trailerUrl: 'https://www.youtube.com/embed/FTjG-Aux_yQ',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0088763',
    title: 'Back to the Future',
    year: 1985,
    genre: ['Adventure', 'Comedy', 'Sci-Fi'],
    imdbRating: 8.5,
    rottenTomatoes: 93,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZmM3ZjE0NzctNjBiOC00MDZmLTgzMTUtNGVlOWFlOTNiZDJiXkEyXkFqcGc@._V1_QL75_UX380_CR0,14,380,562_.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Robert Zemeckis',
    language: 'English',
    runtime: '116 min',
    cast: ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson'],
    trailerUrl: 'https://www.youtube.com/embed/qvsgGtivCgs',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0034583',
    title: 'Casablanca',
    year: 1943,
    genre: ['Drama', 'Romance', 'War'],
    imdbRating: 8.5,
    rottenTomatoes: 99,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNWEzN2U1YTYtYTQyMS00NTVkLWE2NGQtZWFlMmM0MDNjMmRiXkEyXkFqcGc@._V1_QL75_UX380_CR0,5,380,562_.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Michael Curtiz',
    language: 'English, French, German, Italian, Russian',
    runtime: '102 min',
    cast: ['Humphrey Bogart', 'Ingrid Bergman', 'Paul Henreid'],
    trailerUrl: 'https://www.youtube.com/embed/BkL9l7qovsE',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0073195',
    title: 'Jaws',
    year: 1975,
    genre: ['Adventure', 'Horror', 'Thriller'],
    imdbRating: 8.1,
    rottenTomatoes: 97,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYjViNDQzNmUtYzkxZi00NTk5LTljMmItYjJlZmZkODIxNjU1XkEyXkFqcGc@._V1_SX300.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Steven Spielberg',
    language: 'English',
    runtime: '124 min',
    cast: ['Roy Scheider', 'Robert Shaw', 'Richard Dreyfuss'],
    trailerUrl: 'https://www.youtube.com/embed/U1fu_sA7XhE',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0017136',
    title: 'Metropolis',
    year: 1927,
    genre: ['Drama', 'Sci-Fi'],
    imdbRating: 8.2,
    rottenTomatoes: 97,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjhjMGYyMjAtMzJkYy00NzhlLWIwY2MtMWQ2ODIxZDUyOGYyXkEyXkFqcGc@._V1_SX300.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Fritz Lang',
    language: 'German, None',
    runtime: '153 min',
    cast: ['Brigitte Helm', 'Alfred Abel', 'Gustav Fröhlich'],
    trailerUrl: 'https://www.youtube.com/embed/gdtZv3XROnc',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0054215',
    title: 'Psycho',
    year: 1960,
    genre: ['Drama', 'Horror', 'Mystery'],
    imdbRating: 8.5,
    rottenTomatoes: 97,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYjZhMzFiZjItODA3ZC00MmRhLWIzMGYtMmVjOWUwYTA3MTRjXkEyXkFqcGc@._V1_QL75_UX380_CR0,1,380,562_.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Alfred Hitchcock',
    language: 'English',
    runtime: '109 min',
    cast: ['Anthony Perkins', 'Janet Leigh', 'Vera Miles'],
    trailerUrl: 'https://www.youtube.com/embed/DTJQfFQ40lI',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0082971',
    title: 'Raiders of the Lost Ark',
    year: 1981,
    genre: ['Action', 'Adventure'],
    imdbRating: 8.4,
    rottenTomatoes: 94,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BOGNhMjg2ZjgtYzk4Ni00MTViLTg1MmUtYzM2MDZiYjZlMmU3XkEyXkFqcGc@._V1_SX300.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Steven Spielberg',
    language: 'English, German, Spanish, Nepali, Hebrew, Arabic',
    runtime: '115 min',
    cast: ['Harrison Ford', 'Karen Allen', 'Paul Freeman'],
    trailerUrl: 'https://www.youtube.com/embed/Rh_BJXG1-44',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0063522',
    title: "Rosemary's Baby",
    year: 1968,
    genre: ['Drama', 'Horror'],
    imdbRating: 8.0,
    rottenTomatoes: 97,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNDlhMDI3OTQtNTBkYy00NWQ5LWJmNWEtZGQwYzZlMTQ4MDI1XkEyXkFqcGc@._V1_SX300.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Roman Polanski',
    language: 'English',
    runtime: '137 min',
    cast: ['Mia Farrow', 'John Cassavetes', 'Ruth Gordon'],
    trailerUrl: 'https://www.youtube.com/embed/BjpA6IH_Skc',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0102926',
    title: 'The Silence of the Lambs',
    year: 1991,
    genre: ['Crime', 'Drama', 'Horror'],
    imdbRating: 8.6,
    rottenTomatoes: 95,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNDdhOGJhYzctYzYwZC00YmI2LWI0MjctYjg4ODdlMDExYjBlXkEyXkFqcGc@._V1_QL75_UY562_CR1,0,380,562_.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Jonathan Demme',
    language: 'English, Latin',
    runtime: '118 min',
    cast: ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn'],
    trailerUrl: 'https://www.youtube.com/embed/W6Mm8Sbe__o',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0070047',
    title: 'The Exorcist',
    year: 1973,
    genre: ['Horror'],
    imdbRating: 8.1,
    rottenTomatoes: 78,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZjg3YjE4ZjAtYTdmYS00ZTBkLWE1ZjgtNzAzODUwNzRiYjlmXkEyXkFqcGc@._V1_SX300.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'William Friedkin',
    language: 'English, Latin, Greek, French, German, Arabic, Kurdish',
    runtime: '122 min',
    cast: ['Ellen Burstyn', 'Max von Sydow', 'Linda Blair'],
    trailerUrl: 'https://www.youtube.com/embed/PjD42P7BAaA',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0117951',
    title: 'Trainspotting',
    year: 1996,
    genre: ['Crime', 'Drama'],
    imdbRating: 8.1,
    rottenTomatoes: 90,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYmVkNGJkMzQtYWQwOS00OTZmLThjODQtZjNjNzllYzRiNTE0XkEyXkFqcGc@._V1_SX300.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Danny Boyle',
    language: 'English',
    runtime: '93 min',
    cast: ['Ewan McGregor', 'Ewen Bremner', 'Jonny Lee Miller'],
    trailerUrl: 'https://www.youtube.com/embed/8LuxOYIpu-I',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0084787',
    title: 'The Thing',
    year: 1982,
    genre: ['Horror', 'Mystery', 'Sci-Fi'],
    imdbRating: 8.2,
    rottenTomatoes: 85,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYTA3NDU5MWEtNTk4Yy00ZDNkLThmZTQtMjU3ZGVhYzAyMzU4XkEyXkFqcGc@._V1_SX300.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'John Carpenter',
    language: 'English, Norwegian',
    runtime: '109 min',
    cast: ['Kurt Russell', 'Wilford Brimley', 'Keith David'],
    trailerUrl: 'https://www.youtube.com/embed/brPRW-_OcdE',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0076759',
    title: 'Star Wars: Episode IV - A New Hope',
    year: 1977,
    genre: ['Action', 'Adventure', 'Fantasy'],
    imdbRating: 8.6,
    rottenTomatoes: 94,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BOGUwMDk0Y2MtNjBlNi00NmRiLTk2MWYtMGMyMDlhYmI4ZDBjXkEyXkFqcGc@._V1_SX300.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'George Lucas',
    language: 'English',
    runtime: '121 min',
    cast: ['Mark Hamill', 'Harrison Ford', 'Carrie Fisher'],
    trailerUrl: 'https://www.youtube.com/embed/gBKx63Y6rG4',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt1255953',
    title: 'Incendies',
    year: 2010,
    genre: ['Drama', 'Mystery', 'War'],
    imdbRating: 8.3,
    rottenTomatoes: 91,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYWFmMjdmNjctNzhhOC00ZmMzLTkwOGItMmVmZDU4MjE2MTYwXkEyXkFqcGc@._V1_SX300.jpg',
    badge: 'New',
    isFavorite: false,
    director: 'Denis Villeneuve',
    language: 'French, Arabic, English',
    runtime: '131 min',
    cast: ['Lubna Azabal', 'Mélissa Désormeaux-Poulin', 'Maxim Gaudette'],
    trailerUrl: 'https://www.youtube.com/embed/XJ69WnwvZhE',
    dateAdded: RECENTLY_ADDED_DATE,
  },
  {
    id: 'tt0052357',
    title: 'Vertigo',
    year: 1958,
    genre: ['Mystery', 'Romance', 'Thriller'],
    imdbRating: 8.2,
    rottenTomatoes: 93,
    personalRating: 0,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNzEyZTUxMWItMGVhYy00Y2NlLTljYTMtYzBmMzI1YmUyMDBkXkEyXkFqcGc@._V1_QL75_UX380_CR0,13,380,562_.jpg',
    badge: 'Classic',
    isFavorite: false,
    director: 'Alfred Hitchcock',
    language: 'English',
    runtime: '128 min',
    cast: ['James Stewart', 'Kim Novak', 'Barbara Bel Geddes'],
    trailerUrl: 'https://www.youtube.com/embed/Geu4LXm_GlY',
    dateAdded: RECENTLY_ADDED_DATE,
  },
];
